services:
  web:
    build: .
    command: sh -c "python wait_for_db.py &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py shell -c "
from django.contrib.auth import get_user_model;
import os;

User = get_user_model();

username = os.getenv('DJANGO_SUPERUSER_USERNAME');

if not User.objects.filter(username=username).exists():
    User.objects.create_superuser(
        username,
        os.getenv('DJANGO_SUPERUSER_EMAIL'),
        os.getenv('DJANGO_SUPERUSER_PASSWORD')
    )
" &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - .:/usr/src/app/
    
  db:
    image: postgres:14.22-trixie
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_db
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
