name: Python Pull Request Workflow

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    env:
      POETRY_VIRTUALENVS_CREATE: false
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 testserver

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry

      - name: View Poetry
        run: poetry --help

      - name: Install dependencies
        run: poetry install
      
      - name: Export Poetry env
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH    
      
      - name: Test
        run: poetry run python manage.py test

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -reporter=github-pr-check
